"""
Before using this little program, you must take into consideration the following things : 
----> 52% of netusers use the same password for more than one online account.
----> 13% of netusers use the same password for all their accounts.
----> 35% use different password for all accounts
----> Old people who are more than 50 years old, use the same password for all their accounts.
----> 35% of netusers choose passwords easy to memorize as their account password.
These passwords can be their name, surname, family members' name, date of birth, pets'name or
their favorite stars'name(football player, basketball player, singer), their country, their city,
the year they created the password. 
It more generally related to their activities, their leisures.
----> 66% of netusers create a new password based on their previous password
----> Some of the netusers write their passwords on a paper or share with some of their relative.
----> The average length of passwords is 8 characters.
----> Their some websites which don't allow special characters when setting a password.
----> 59% of netusers use their name or birthday in their password.
----> 67% of passwords start with a letter(let's say generally an uppercase due to the phone keyboard,
      knowing that 92% of internet users access the internet using a mobile phone).
----> 42% of organizations rely on sticky notes for password management 
----> Most of the time, as special character, they use .-_,?!
Also, it important to adopt good manners for setting a good password : 
----> Use a non-predictable password which is non related to you(this can be done by using a password generator)
----> Use unknown special character(For example, you can use ' '#^:~&)#
----> Use a passphrase(length : 20 or 30 characters) rather than a password excepts if the password was
      generated by a password generator and if it has a length of 12 characters minimum.
"""
import time
from getpass import getpass
from password_characteristics import *
from password_characters_occurences import *
from password_generator import *
from check_name_surname_birthday_in_password import *
from test_password import *
from check_name_surname_country_city_format import *

if __name__ == '__main__':
    user_password = getpass('Enter your password : ')
    print("Note : You can use rockyou dictionary available in the project directory : ")
    dictionary_path = input('Enter the dictionary absolute path(C:/...) : ')
    user_first_name = input('Enter your first name : ')
    user_last_names = input('Enter your last_names(in case of several names, use a space as a separator) : ')
    user_birthday = input('Enter your birthday(format : DD/MM/YYYY or DD-MM-YYYY) : ')
    user_country = input('Enter your country(ex : Mali) : ')
    user_city = input('Enter your city(ex: Bamako) : ')
    check_name_surname_country_city_format(user_first_name, user_last_names.split(), user_country, user_city)
    test_password(user_password, dictionary_path)

    print("Let's now inspect the words and characters used in your password :}")
    password_characters_occurences_dict, alphanumerical_characters_list = get_password_characters_occurences(user_password)
    check_password_characters_mixture(password_characters_occurences_dict, alphanumerical_characters_list)
    check_name_surname_birthday_city_in_password(user_password, user_first_name, user_last_names, user_birthday, user_country, user_city)

    user_response = input('Do you wanna generate a password through our password generator : ')
    if user_response.lower() in ['y','yes','yep','yeah'] :
        password_generator()
    print("──────────────────────────────────────────────────────────────────────────────────────────\n")
    print('A BIG THANK to you for having tried this little program')
    print('Hope that you enjoyed it :)\nSee you soon amigo (^_-)')
    time.sleep(2)
    print("Hmmm last thing : if your password was considered as weak, don't forget to CHANGE it (^.^)")